@echo off
setlocal
cd /d "%~dp0"
set "PYTHONIOENCODING=utf-8"
set "LLM_PROVIDER=lmstudio"
set "LMSTUDIO_BASE_URL=http://127.0.0.1:1234"
set "SCRIPT_LLM_MODEL=google/gemma-4-e4b"
set "LMSTUDIO_CONTEXT_TARGET=72000"
set "NEWAUTO_USE_EXISTING_LMSTUDIO_MODEL=1"
set "OPENROUTER_MODEL_REVIEWER=google/gemma-4-31b-it:free"
set "OPENROUTER_MODEL_PLANNER=google/gemma-4-31b-it:free"
set "OPENROUTER_MODEL_DEBUGGER=google/gemma-4-31b-it:free"
set "OPENROUTER_MODEL_CODER=google/gemma-4-31b-it:free"
set "OPENROUTER_FALLBACK_MODEL=google/gemma-4-26b-a4b-it:free"
set "OPENROUTER_LAST_RESORT_MODEL=openai/gpt-oss-20b:free"
if not defined OPENROUTER_API_KEY if exist "%~dp0openrouter.txt" for /f "usebackq tokens=* delims=" %%K in ("%~dp0openrouter.txt") do if not defined OPENROUTER_API_KEY if not "%%K"=="" set "OPENROUTER_API_KEY=%%K"
set "NEWAUTO_API_PORT=9002"
set "NEWAUTO_BASE_URL=http://127.0.0.1:%NEWAUTO_API_PORT%"
set "FLOW_AUTOMATION_BACKEND=playwright"
set "FLOW_MODE=playwright"
set "FLOW_BROWSER=edge"
set "FLOW_PROMPT_SUBMIT_DELAY_SECONDS=15"
set "FLOW_GENERATE_COOLDOWN_SECONDS=90"
"C:\Users\petbl\local-rag\.venv\Scripts\python.exe" "%~dp0scripts\newauto_stepwise_mcp.py" %*
